# Generated by Django 3.2.7 on 2021-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('height_ft', models.PositiveSmallIntegerField()),
                ('height_in', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
