# Generated by Django 3.2.7 on 2021-09-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('E', 'Empacher'), ('M', 'Millenium'), ('R', 'Resolute')], max_length=30)),
                ('size', models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('P', 'Pair'), ('CF', 'Coxed Four'), ('SF', 'Straight Four'), ('Q', 'Quad'), ('E', 'Eight')], max_length=20)),
                ('year', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='rower',
            name='mmr',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rower',
            name='stroke_mmr',
            field=models.PositiveSmallIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('crewmember', models.ManyToManyField(to='athletes.Rower')),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.hull')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
