# Generated by Django 3.2.7 on 2021-09-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20210926_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hull',
            options={'ordering': ['year']},
        ),
    ]
