# Generated by Django 3.2.7 on 2021-09-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_hull_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rower',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='boat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hull',
            name='make',
            field=models.CharField(choices=[('EMPCH', 'Empacher'), ('MILL', 'Millenium'), ('RESOL', 'Resolute')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hull',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
