# Generated by Django 3.2.7 on 2021-09-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20210926_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hull',
            name='make',
            field=models.CharField(choices=[('Empacher', 'Empacher'), ('Millenium', 'Millenium'), ('Resolute', 'Resolute')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hull',
            name='size',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Pair', 'Pair'), ('Coxed Four', 'Coxed Four'), ('Straight Four', 'Straight Four'), ('Quad', 'Quad'), ('Eight', 'Eight')], max_length=20),
        ),
    ]
