# Generated by Django 3.2.7 on 2021-10-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_auto_20210926_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='crewmember',
            new_name='crewmembers',
        ),
    ]
