# Generated by Django 3.2.7 on 2021-10-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_rename_crewmember_boat_crewmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rower',
            old_name='stroke_mmr',
            new_name='mmr_uncertainty',
        ),
    ]
