# Generated by Django 3.2.7 on 2021-10-20 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_rename_stroke_mmr_rower_mmr_uncertainty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('draw', models.BooleanField()),
                ('loser_crew', models.ManyToManyField(related_name='loser_crew', to='athletes.Rower')),
                ('loser_hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_hull', to='athletes.hull')),
                ('winner_crew', models.ManyToManyField(related_name='winner_crew', to='athletes.Rower')),
                ('winner_hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_hull', to='athletes.hull')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Boat',
        ),
    ]
